# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           ':/title'
relative_permalinks: true

# Setup
title:               Kaviraj
tagline:             notes. thoughts
description:	     Kaviraj's notes & thoughts
url:                 https://kavirajk.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kaviraj Kanagaraj
  url:               https://twitter.com/kvrajk
  email:             kavirajkanagaraj@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kavirajk/kavirajk.github.io

# Conversion
excerpt_separator: "<!--break-->"

pages_list:
  Archive: '/archive'
  Tags: '/tags/'
